name: build&sync
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      env:
        description: environment
        default: dev
        required: true
jobs:
  set_env:
    outputs:
      env: ${{ steps.setenv.outputs.env }}
      dest-branch: ${{ steps.dest-branch.outputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - id: setenv
        run: |
          if test -n "${{ github.event.inputs.env }}"
          then
            echo "::set-output name=env::${{ github.event.inputs.env }}"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/develop'
          then
            echo "::set-output name=env::dev"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/main'
          then
            echo "::set-output name=env::prod"
          fi
      - id: dest-branch
        run: |
          case ${{ setenv.outputs.env }} in
            dev)
            echo "::set-output name=branch::develop"
            ;;
            prod)
            echo "::set-output name=branch::main"
            ;;
          esac
  build-and-deploy:
    needs: set_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: echo environment
        run: |
          echo "::notice ::env:${{needs.set_env.outputs.env}}"
          echo "::notice ::dest-branch:${{needs.set_env.outputs.dest-branch}}"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install notebook
      - run: jupyter nbconvert --output-dir='build' --to html docs/source/notebooks/*.ipynb --no-prompt
      - run: ls -la build
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: build/
          retention-days: 7
      - uses: cpina/github-action-push-to-another-repository@cbe757f8d8b380dd2b3ceec5a80fbcd61f1f3107 #1.7
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-directory: 'build'
          destination-github-username: JunchengXue
          destination-repository-name: tidy3d
          user-name: bot
          user-email: bot@flexcompute.com
          target-branch: ${{ needs.set_env.outputs.dest-branch }}
          target-directory: img/html
