name: sync
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      env:
        description: environment
        default: dev
        required: true
jobs:
  set_env:
    outputs:
      env: ${{ steps.setenv.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - id: setenv
        run: |
          if test -n "${{ github.event.inputs.env }}"
          then
            echo "::set-output name=env::${{ github.event.inputs.env }}"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/develop'
          then
            echo "::set-output name=env::dev"
          fi
          if test "${{ github.event_name }}" = 'push' -a "${{ github.ref }}" = 'refs/heads/main'
          then
            echo "::set-output name=env::prod"
          fi
  build-and-deploy:
    needs: set_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: echo environment
        run: echo "::notice ::GIT_BRANCH:${{needs.set_env.outputs.env}}"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install notebook
      - run: jupyter nbconvert --output-dir='build' --to script docs/source/notebooks/StartHere.ipynb --no-prompt
      - run: ls -la build
      - uses: actions/upload-artifact@v3
        with:
          name: StartHere
          path: build/
